[package]
name = "sequioa-autocrypt-store"
version = "0.1.0"
edition = "2021"
authors = ["Per Odlund <odlund@posteo.net>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
sequoia-openpgp = "1.13.0"
